title   AmiCachy - Install to Disk
linux   /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-cachyos
initrd  /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-cachyos.img
options archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% amiprofile=installer quiet splash loglevel=0 rd.systemd.show_status=false rd.udev.log_priority=3 udev.log_priority=3 systemd.show_status=false fbcon=nodefer logo.nologo vt.global_cursor_default=0 nvidia-drm.modeset=1 nvidia-drm.fbdev=1 nouveau.modeset=0 module_blacklist=nouveau
