title   AmiCachy - Classic 68k
linux   /vmlinuz-linux-cachyos
initrd  /initramfs-linux-cachyos.img
options root=LABEL=AMICACHY rw quiet splash loglevel=0 rd.systemd.show_status=false rd.udev.log_priority=3 udev.log_priority=3 systemd.show_status=false fbcon=nodefer logo.nologo vt.global_cursor_default=0 amiprofile=classic_68k mitigations=off nowatchdog nvidia-drm.modeset=1 nvidia-drm.fbdev=1 nouveau.modeset=0 module_blacklist=nouveau
